export const paragraphs_en = [
   
    
    { timer: 30, text: "The sun dipped below the horizon, painting the sky in shades of orange and purple." },
  { timer: 30, text: "A gentle breeze carried the scent of jasmine through the quiet streets." },
  { timer: 35, text: "She opened the old book, its pages yellowed with time and filled with forgotten stories." },
  { timer: 30, text: "The city buzzed with life, neon lights flickering against the night sky." },
  { timer: 35, text: "Raindrops tapped softly against the window, a lullaby for the restless mind." },
  { timer: 35, text: "He walked along the shore, leaving footprints that the waves quickly erased." },
  { timer: 30, text: "The mountain stood tall and silent, a guardian of the valley below." },
  { timer: 30, text: "Children’s laughter echoed in the park, mingling with the chirping of birds." },
  { timer: 30, text: "The clock ticked steadily, marking the passage of moments too easily lost." },
  { timer: 30, text: "She sipped her tea slowly, savoring the warmth that spread through her hands." },
  { timer: 45, text: "The library smelled of paper and ink, a sanctuary for curious souls." },
  { timer: 50, text: "Stars scattered across the sky like diamonds on a velvet canvas." },
  { timer: 20, text: "He adjusted his glasses, focusing on the puzzle that refused to be solved." },
  { timer: 60, text: "The marketplace was alive with colors, sounds, and the aroma of spices." },
  { timer: 30, text: "A cat stretched lazily in the sunbeam, purring with contentment." },
  { timer: 30, text: "The train rumbled forward, carrying dreams and strangers alike." },
  { timer: 30, text: "She traced her finger along the map, imagining journeys yet to come." },
  { timer: 30, text: "The fire crackled in the hearth, casting dancing shadows on the walls." },
  { timer: 30, text: "He paused at the crossroads, uncertain which path would lead him home." },
  { timer: 30, text: "The garden bloomed in a riot of colors, a celebration of spring’s return." }
    ,
{ timer: 30, text: "The lantern swayed gently, casting golden ripples across the cobblestone path." },
{ timer: 35, text: "She tucked the letter into her coat, its words still echoing in her mind." },
{ timer: 30, text: "The wind rustled through the trees, whispering secrets only the forest could keep." },
{ timer: 30, text: "Footsteps faded into the distance, leaving behind silence and a trail of memories." },
{ timer: 45, text: "The café hummed with quiet conversation, steam curling from cups of coffee and tea." },
{ timer: 30, text: "He stared at the blank canvas, waiting for inspiration to strike like lightning." },
{ timer: 35, text: "The moon hung low, a silver guardian watching over the sleeping town." },
{ timer: 30, text: "She ran her fingers over the piano keys, each note a thread in her story." },
{ timer: 30, text: "The suitcase lay open, half-packed with clothes and half-filled with hesitation." },
{ timer: 30, text: "A dog barked in the distance, its voice cutting through the evening calm." },
{ timer: 50, text: "The bridge arched gracefully over the river, connecting two worlds with quiet dignity." },
{ timer: 30, text: "He lit a candle, its flame flickering like hope in the dark." },
{ timer: 30, text: "The old radio crackled to life, playing a tune from a forgotten decade." },
{ timer: 35, text: "She watched the rain trace paths down the glass, each droplet a tiny journey." },
{ timer: 30, text: "The attic smelled of dust and dreams, filled with relics of lives once lived." },
{ timer: 30, text: "He folded the paper crane carefully, a gesture of peace in a chaotic world." },
{ timer: 30, text: "The lighthouse blinked steadily, guiding ships through fog and memory." },
{ timer: 30, text: "She closed her eyes and listened, letting the music carry her somewhere else." },
{ timer: 30, text: "The garden gate creaked open, revealing a path lined with wildflowers and wonder." },
{ timer: 30, text: "He scribbled in his notebook, each word a step closer to understanding." },

{ timer: 35, text: "The violin’s melody drifted through the night, fragile yet unbreakable." },
{ timer: 30, text: "She tied her hair back, ready to face the day’s quiet battles." },
{ timer: 30, text: "The waves shimmered under the moonlight, silver threads woven into the sea." },
{ timer: 30, text: "He leaned against the lamppost, lost in thoughts heavier than the night air." },
{ timer: 45, text: "The bakery’s warmth spilled into the street, carrying the scent of fresh bread." },
{ timer: 30, text: "She traced constellations with her finger, mapping stories across the stars." },
{ timer: 35, text: "The fountain gurgled softly, its rhythm steady as a heartbeat." },
{ timer: 30, text: "He placed the photograph back on the shelf, dust settling like memory." },
{ timer: 30, text: "The meadow swayed in unison, a green ocean beneath the sky." },
{ timer: 30, text: "She whispered a wish into the wind, hoping it would find its way." },
{ timer: 50, text: "The cathedral bells tolled, their echoes rolling across the rooftops." },
{ timer: 30, text: "He brushed the sand from his shoes, carrying the shore with him." },
{ timer: 30, text: "The lanterns floated upward, tiny suns drifting into the night." },
{ timer: 35, text: "She lingered at the station, the sound of departures heavy in her chest." },
{ timer: 30, text: "The orchard was alive with blossoms, petals falling like snow." },
{ timer: 30, text: "He tapped his pen against the desk, words refusing to come." },
{ timer: 30, text: "The horizon glowed faintly, promising the arrival of dawn." },
{ timer: 30, text: "She hummed a lullaby, her voice soft as falling rain." },
{ timer: 30, text: "The alley smelled of rain and stone, a secret world between streets." },
{ timer: 30, text: "He adjusted his scarf, the cold biting sharper than memory." },

{ timer: 35, text: "The carousel spun slowly, its painted horses frozen in eternal gallop." },
{ timer: 30, text: "She dipped her brush in paint, colors blooming across the canvas." },
{ timer: 30, text: "The forest floor crackled underfoot, alive with hidden creatures." },
{ timer: 30, text: "He leaned out the window, the city’s heartbeat pulsing below." },
{ timer: 45, text: "The marketplace glittered with lanterns, each stall a world of its own." },
{ timer: 30, text: "She folded the blanket neatly, the scent of lavender clinging to it." },
{ timer: 35, text: "The horizon blurred where sea met sky, endless and unknowable." },
{ timer: 30, text: "He polished the old watch, its ticking steady as time itself." },
{ timer: 30, text: "The sparrows darted between branches, stitching the air with song." },
{ timer: 30, text: "She lingered by the fountain, her reflection rippling with the water." }
    ,
{ timer: 40, text: "The desert stretched endlessly, dunes shifting like waves frozen in time." },
{ timer: 30, text: "She pressed a flower between the pages, preserving a moment of spring." },
{ timer: 35, text: "The subway roared beneath the city, carrying stories in every carriage." },
{ timer: 30, text: "He traced the graffiti on the wall, colors shouting louder than words." },
{ timer: 45, text: "The storm rolled in, thunder shaking the windows like a warning drum." },
{ timer: 30, text: "She lit incense, the smoke curling into shapes that vanished too soon." },
{ timer: 30, text: "The glacier groaned, ancient ice shifting under the weight of centuries." },
{ timer: 30, text: "He leaned over the balcony, neon lights painting his face in shifting hues." },
{ timer: 35, text: "The violin case lay open, velvet cradling silence where music once lived." },
{ timer: 30, text: "She scribbled a note on the napkin, words hurried but heartfelt." },

{ timer: 30, text: "The jungle pulsed with life, unseen creatures calling into the night." },
{ timer: 30, text: "He adjusted the telescope, stars swimming into focus like old friends." },
{ timer: 50, text: "The skyscraper’s glass reflected the sunset, a fire trapped in steel." },
{ timer: 30, text: "She tucked the photograph into her pocket, a talisman against loneliness." },
{ timer: 30, text: "The canyon echoed with wind, a voice older than memory." },
{ timer: 35, text: "He tapped the typewriter keys, each click a spark in the dark." },
{ timer: 30, text: "The lanterns bobbed on the river, drifting like dreams set free." },
{ timer: 30, text: "She brushed dust from the mirror, her reflection blurred by time." },
{ timer: 30, text: "The marketplace shimmered with holograms, vendors calling in digital chorus." },
{ timer: 30, text: "He paused at the mural, colors alive with stories of the street." },

{ timer: 45, text: "The volcano smoked quietly, a reminder of fire beneath the earth." },
{ timer: 30, text: "She folded the letter carefully, sealing it with trembling hands." },
{ timer: 30, text: "The drone buzzed overhead, its shadow crossing the alley like a hawk." },
{ timer: 30, text: "He scrolled through old messages, each word a ghost of conversation." },
{ timer: 35, text: "The aurora rippled across the sky, green fire dancing with the stars." },
{ timer: 30, text: "She tied the ribbon around the gift, a small act of quiet joy." },
{ timer: 30, text: "The ruins stood silent, ivy reclaiming what stone once defied." },
{ timer: 30, text: "He leaned against the jukebox, music spilling into the smoky bar." },
{ timer: 30, text: "The holographic billboard flickered, selling dreams in neon light." },
{ timer: 30, text: "She traced her name in the sand, waves rushing to erase it." },

{ timer: 50, text: "The rainforest canopy glowed with bioluminescence, a galaxy beneath leaves." },
{ timer: 30, text: "He wound the pocket watch, gears ticking like a heartbeat." },
{ timer: 30, text: "The alley cat darted between shadows, eyes gleaming like lanterns." },
{ timer: 30, text: "She whispered into the seashell, pretending it could carry her words." },
{ timer: 35, text: "The observatory dome opened, revealing the infinite night." },
{ timer: 30, text: "He poured another cup of coffee, steam rising like morning prayers." },
{ timer: 30, text: "The desert wind howled, sculpting dunes into fleeting monuments." },
{ timer: 30, text: "She adjusted the record player, the needle crackling into song." },
{ timer: 30, text: "The skyline shimmered, skyscrapers piercing clouds like needles." },
{ timer: 30, text: "He paused at the fountain, coins glinting with unspoken wishes." },

{ timer: 45, text: "The cave glittered with crystals, light refracting into hidden rainbows." },
{ timer: 30, text: "She tucked the scarf tighter, the night colder than expected." },
{ timer: 30, text: "The tram rattled along the tracks, sparks flying beneath its wheels." },
{ timer: 30, text: "He scribbled formulas on the chalkboard, chasing answers in dust." },
{ timer: 35, text: "The meadow glowed with fireflies, tiny lanterns swaying in the dark." },
{ timer: 30, text: "She hummed softly, her voice blending with the hum of machines." },
{ timer: 30, text: "The ruins of the temple stood proud, stone guardians of forgotten gods." },
{ timer: 30, text: "He leaned against the vending machine, neon buzzing overhead." },
{ timer: 30, text: "The rain turned the streets into mirrors, reflecting a city upside down." },
{ timer: 30, text: "She closed the music box, its last note lingering in the air." }
,
{ timer: 40, text: "The sky rippled like water, clouds swimming as though the heavens were an ocean." },
{ timer: 35, text: "She stepped onto the staircase that spiraled upward into nothingness." },
{ timer: 30, text: "The clock melted across the wall, its hands dripping into pools of time." },
{ timer: 30, text: "He opened the door to find a forest where his kitchen should have been." },
{ timer: 45, text: "The moon split into three, each orb casting a different color of light." },
{ timer: 30, text: "She floated above the street, her shadow walking calmly below." },
{ timer: 30, text: "The river flowed upward into the sky, carrying fish like shooting stars." },
{ timer: 30, text: "He reached for the mirror and found his reflection reaching back." },
{ timer: 35, text: "The library’s shelves stretched endlessly, books whispering as they shifted." },
{ timer: 30, text: "She walked across the lake’s surface, ripples blooming beneath her steps." },

{ timer: 30, text: "The horizon bent inward, folding the world like paper." },
{ timer: 30, text: "He found a staircase descending into the clouds, each step softer than air." },
{ timer: 50, text: "The stars rearranged themselves into words only she could read." },
{ timer: 30, text: "She opened her umbrella indoors and drifted upward like a balloon." },
{ timer: 30, text: "The city’s buildings leaned closer, whispering secrets through their windows." },
{ timer: 35, text: "He touched the tree and felt it pulse with a heartbeat of its own." },
{ timer: 30, text: "The rain fell upward, returning to the clouds in silver streams." },
{ timer: 30, text: "She found a keyhole in the sky, and the stars turned to watch." },
{ timer: 30, text: "The ground beneath him turned to glass, revealing galaxies below." },
{ timer: 30, text: "She blinked, and the street lamps became glowing eyes." },

{ timer: 45, text: "The horizon cracked open, spilling light like molten gold." },
{ timer: 30, text: "He walked into the painting, colors wrapping around him like fabric." },
{ timer: 30, text: "The birds flew backward, wings beating against the flow of time." },
{ timer: 30, text: "She whispered into the well, and the echo answered with her own voice." },
{ timer: 35, text: "The mountains floated above the valley, their roots dangling like threads." },
{ timer: 30, text: "He opened the book and a breeze carried the words into the air." },
{ timer: 30, text: "The statues turned their heads as she passed, stone eyes alive with curiosity." },
{ timer: 30, text: "The river split into dozens of smaller streams, each glowing with color." },
{ timer: 30, text: "She reached for the candle flame and found it cool to the touch." },
{ timer: 30, text: "The horizon looped endlessly, the sun rising and setting in seconds." },

{ timer: 50, text: "The forest grew upside down, roots stretching toward the stars." },
{ timer: 30, text: "He stepped into the shadow and emerged in another street." },
{ timer: 30, text: "The clouds shaped themselves into doors, waiting to be opened." },
{ timer: 30, text: "She found her reflection smiling when she was not." },
{ timer: 35, text: "The desert bloomed with flowers that sang in the wind." },
{ timer: 30, text: "He followed the staircase that led sideways into the horizon." },
{ timer: 30, text: "The moonlight dripped like water, pooling in silver puddles." },
{ timer: 30, text: "She touched the horizon and it rippled like fabric." },
{ timer: 30, text: "The stars fell like snow, melting as they touched the ground." },
{ timer: 30, text: "He opened the window and found an ocean instead of sky." },

{ timer: 45, text: "The city floated above the earth, tethered by threads of light." },
{ timer: 30, text: "She walked through the rain without getting wet, each drop bending away." },
{ timer: 30, text: "The clock tower chimed thirteen, and the world held its breath." },
{ timer: 30, text: "He stepped into his shadow and vanished from sight." },
{ timer: 35, text: "The flowers glowed softly, illuminating the night with their breath." },
{ timer: 30, text: "She found a staircase carved into the moonlight itself." },
{ timer: 30, text: "The horizon tilted, and the sea poured into the sky." },
{ timer: 30, text: "He reached for the star and felt it pulse warmly in his hand." },
{ timer: 30, text: "The streets rearranged themselves, leading her in circles of wonder." },
{ timer: 30, text: "She closed her eyes and floated upward, carried by invisible wings." },


    { timer: 30, text: "The candle burned low, its flame steady against the quiet night." },
{ timer: 30, text: "She folded the blanket around her shoulders, comfort in its familiar weight." },
{ timer: 30, text: "The garden rested under moonlight, blossoms closed in peaceful slumber." },
{ timer: 30, text: "He set the book aside, words lingering like echoes in his mind." },
{ timer: 35, text: "The waves lapped gently at the shore, a rhythm older than memory." },
{ timer: 30, text: "She closed the window, the night air carrying a final whisper of jasmine." },
{ timer: 30, text: "The village lights twinkled in the valley, each one a story at rest." },
{ timer: 30, text: "He leaned back in the chair, listening to the steady ticking of the clock." },
{ timer: 30, text: "The stars shimmered softly, patient witnesses to countless nights." },
{ timer: 30, text: "She placed the letter in a drawer, not forgotten but gently kept." },

{ timer: 40, text: "The fire dimmed to embers, glowing with the warmth of what had been." },
{ timer: 30, text: "He traced the outline of the horizon, where day and night shook hands." },
{ timer: 30, text: "The cat curled into a ball, purring softly in its dream." },
{ timer: 30, text: "She let the teacup cool, savoring the last sip in silence." },
{ timer: 35, text: "The wind quieted, leaving the trees to rest in stillness." },
{ timer: 30, text: "He closed his journal, the ink drying on words meant only for himself." },
{ timer: 30, text: "The lantern’s glow faded, leaving the room in gentle shadow." },
{ timer: 30, text: "She smiled faintly, her thoughts drifting like leaves on water." },
{ timer: 30, text: "The night wrapped the world in a soft, forgiving hush." },
{ timer: 30, text: "He exhaled slowly, the weight of the day dissolving into calm." },

{ timer: 45, text: "The meadow lay quiet under starlight, a quilt of silver and green." },
{ timer: 30, text: "She rested her head against the window, watching the moon follow the train." },
{ timer: 30, text: "The old house creaked softly, settling into its own kind of sleep." },
{ timer: 30, text: "He placed the photograph back on the shelf, content to let it rest." },
{ timer: 35, text: "The tide receded, leaving seashells glistening like forgotten jewels." },
{ timer: 30, text: "She whispered goodnight to the empty room, and it seemed to listen." },
{ timer: 30, text: "The orchard stood still, branches heavy with the promise of tomorrow." },
{ timer: 30, text: "He leaned against the porch rail, breathing in the cool night air." },
{ timer: 30, text: "The stars blurred softly as her eyes grew heavy with sleep." },
{ timer: 30, text: "She closed the diary, its pages safe with secrets and dreams." },

{ timer: 40, text: "The hills faded into shadow, their outlines softened by dusk." },
{ timer: 30, text: "He placed the guitar aside, the last chord still humming in the air." },
{ timer: 30, text: "The path home glowed faintly under the lantern’s watchful eye." },
{ timer: 30, text: "She lingered at the doorway, grateful for the quiet within." },
{ timer: 35, text: "The night sky deepened, a canvas of velvet and silver." },
{ timer: 30, text: "He let the pen rest, the page filled with thoughts now at peace." },
{ timer: 30, text: "The garden gate closed softly, a promise to return another day." },
{ timer: 30, text: "She pulled the quilt tighter, the warmth of home surrounding her." },
{ timer: 30, text: "The silence was not empty, but full of gentle presence." },
{ timer: 30, text: "He smiled faintly, knowing tomorrow would come in its own time." },

{ timer: 45, text: "The horizon softened, blending night and dawn in quiet harmony." },
{ timer: 30, text: "She let her eyes close, the world fading into a gentle dream." },
{ timer: 30, text: "The lamp flickered once, then settled into steady light." },
{ timer: 30, text: "He leaned back, listening to the crickets sing their patient song." },
{ timer: 35, text: "The air cooled, carrying with it the scent of pine and earth." },
{ timer: 30, text: "She placed the last dish away, the kitchen humming with stillness." },
{ timer: 30, text: "The stars wheeled slowly, marking time in silence." },
{ timer: 30, text: "He rested his hand on the windowsill, feeling the night settle in." },
{ timer: 30, text: "The world seemed to pause, balanced between endings and beginnings." },
{ timer: 30, text: "She breathed deeply, her heart steady, her spirit at rest." }
];
export const paragraphs_es = [
    { timer: 30, text: "El cielo se abrió en tonos de cobre, como si la tarde respirara fuego." },
{ timer: 30, text: "Las hojas danzaban en espirales, obedeciendo a un viento invisible." },
{ timer: 30, text: "El río guardaba secretos, reflejando estrellas que aún no habían nacido." },
{ timer: 30, text: "Un farol solitario iluminaba la calle como un guardián cansado." },
{ timer: 35, text: "Las montañas parecían dormir, envueltas en mantas de neblina." },
{ timer: 30, text: "El reloj marcaba la hora con un eco que atravesaba la piel." },
{ timer: 30, text: "Las ventanas brillaban como ojos atentos en la penumbra." },
{ timer: 30, text: "El mar respiraba lento, como si soñara con la luna." },
{ timer: 30, text: "Un gato cruzó el tejado, dejando huellas de silencio." },
{ timer: 30, text: "Las campanas sonaron, y el aire se llenó de memorias." },

{ timer: 30, text: "El horizonte se curvó, abrazando la última chispa del sol." },
{ timer: 30, text: "Las sombras crecieron largas, como si quisieran tocar el cielo." },
{ timer: 30, text: "Un niño sopló burbujas que flotaron como planetas diminutos." },
{ timer: 30, text: "El bosque susurraba nombres que nadie recordaba." },
{ timer: 35, text: "La lluvia pintaba círculos perfectos sobre el estanque." },
{ timer: 30, text: "Un pájaro solitario trazó una línea de fuego en el aire." },
{ timer: 30, text: "Las estrellas se encendieron como lámparas olvidadas." },
{ timer: 30, text: "El viento arrastró pétalos que parecían fragmentos de luna." },
{ timer: 30, text: "Un puente de piedra guardaba historias en su silencio." },
{ timer: 30, text: "Las nubes se abrieron como páginas de un libro secreto." },

{ timer: 30, text: "El amanecer llegó despacio, como un suspiro contenido." },
{ timer: 30, text: "Las olas rompían con la cadencia de un corazón dormido." },
{ timer: 30, text: "Un faro giraba, dibujando círculos de esperanza." },
{ timer: 30, text: "El campo olía a tierra mojada y promesas antiguas." },
{ timer: 35, text: "Las luciérnagas encendieron la noche como un coro de estrellas." },
{ timer: 30, text: "Un tren lejano cantaba su despedida en la oscuridad." },
{ timer: 30, text: "Las montañas reflejaban un azul imposible." },
{ timer: 30, text: "El silencio pesaba como un manto de terciopelo." },
{ timer: 30, text: "Un perro ladró a la luna, como si pudiera alcanzarla." },
{ timer: 30, text: "Las calles vacías guardaban pasos invisibles." },

{ timer: 30, text: "El sol se escondió tras un velo de nubes doradas." },
{ timer: 30, text: "Las campanas del pueblo marcaron un tiempo sin dueño." },
{ timer: 30, text: "Un río secreto corría bajo la ciudad dormida." },
{ timer: 30, text: "El aire olía a pan recién horneado y calma." },
{ timer: 35, text: "Las estrellas se reflejaban en los charcos como espejos rotos." },
{ timer: 30, text: "Un colibrí suspendido parecía desafiar al tiempo." },
{ timer: 30, text: "Las montañas se tiñeron de púrpura al caer la tarde." },
{ timer: 30, text: "El viento jugaba con las cortinas como un niño curioso." },
{ timer: 30, text: "Un barco solitario se deslizaba hacia el horizonte." },
{ timer: 30, text: "Las flores cerraron sus ojos al caer la noche." },

{ timer: 30, text: "El cielo nocturno parecía un tapiz bordado de fuego." },
{ timer: 30, text: "Las sombras bailaban al compás de una vela temblorosa." },
{ timer: 30, text: "Un búho vigilaba desde lo alto, sabio y paciente." },
{ timer: 30, text: "El río cantaba canciones que nadie había escrito." },
{ timer: 35, text: "Las nubes se deshicieron en lágrimas de plata." },
{ timer: 30, text: "Un niño dormía abrazado a un sueño imposible." },
{ timer: 30, text: "El horizonte brillaba como una promesa lejana." },
{ timer: 30, text: "Las estrellas guiaban a los viajeros invisibles." },
{ timer: 30, text: "Un suspiro recorrió la ciudad como un viento suave." },
{ timer: 30, text: "La noche cerró los ojos del mundo con ternura." }
];
export const paragraphs_ar =[
    { timer: 30, text: "السماء انفتحت كستارة من حرير أزرق، تتنفس ببطء." },
{ timer: 30, text: "الأشجار همست بأغنية لا يسمعها سوى الليل." },
{ timer: 30, text: "النهر حمل انعكاس القمر كأنه سر محفوظ." },
{ timer: 30, text: "مصباح وحيد أضاء الطريق مثل قلب ساهر." },
{ timer: 35, text: "الجبال التحفت بالضباب كأنها تغفو في حضن الغيم." },
{ timer: 30, text: "الساعة دقت بنغمة تشبه نبض بعيد." },
{ timer: 30, text: "النوافذ لمعت كعيون يقظة في العتمة." },
{ timer: 30, text: "البحر تنفس ببطء، يحلم بالنجوم." },
{ timer: 30, text: "قطة عبرت السطح تاركة آثار صمتها." },
{ timer: 30, text: "الأجراس رنّت، فامتلأ الهواء بالذكريات." },

{ timer: 30, text: "الأفق انحنى ليعانق آخر شعاع للشمس." },
{ timer: 30, text: "الظلال امتدت طويلة كأنها تبحث عن السماء." },
{ timer: 30, text: "طفل نفخ فقاعات طارت ككواكب صغيرة." },
{ timer: 30, text: "الغابة همست بأسماء منسية." },
{ timer: 35, text: "المطر رسم دوائر كاملة على سطح البركة." },
{ timer: 30, text: "طائر وحيد خطّ خطاً من نار في الهواء." },
{ timer: 30, text: "النجوم أضيئت كفوانيس قديمة." },
{ timer: 30, text: "الريح حملت بتلات كأنها شظايا قمر." },
{ timer: 30, text: "الجسر الحجري خبأ قصصاً في صمته." },
{ timer: 30, text: "السحب انفتحت كصفحات كتاب سري." },

{ timer: 30, text: "الفجر جاء ببطء كزفرة محبوسة." },
{ timer: 30, text: "الأمواج تكسرت بإيقاع قلب نائم." },
{ timer: 30, text: "المنارة دارت، ترسم دوائر من أمل." },
{ timer: 30, text: "الحقل فاح برائحة الأرض المبتلة." },
{ timer: 35, text: "اليراعات أضاءت الليل كجوقة من نجوم." },
{ timer: 30, text: "قطار بعيد غنّى وداعه في الظلام." },
{ timer: 30, text: "الجبال انعكست بلون أزرق مستحيل." },
{ timer: 30, text: "الصمت ثقل كعباءة من مخمل." },
{ timer: 30, text: "كلب نبح على القمر كأنه يطال النجوم." },
{ timer: 30, text: "الشوارع الفارغة احتفظت بخطوات غير مرئية." },

{ timer: 30, text: "الشمس اختبأت خلف ستار من غيوم ذهبية." },
{ timer: 30, text: "أجراس القرية أعلنت وقتاً بلا مالك." },
{ timer: 30, text: "نهر خفي جرى تحت المدينة النائمة." },
{ timer: 30, text: "الهواء امتلأ برائحة الخبز الدافئ." },
{ timer: 35, text: "النجوم انعكست في البرك كقطع مرايا مكسورة." },
{ timer: 30, text: "طائر الطنان وقف متحدياً الزمن." },
{ timer: 30, text: "الجبال تلونت بالأرجوان عند الغروب." },
{ timer: 30, text: "الريح لعبت بالستائر كطفل فضولي." },
{ timer: 30, text: "قارب وحيد انزلق نحو الأفق." },
{ timer: 30, text: "الأزهار أغلقت عيونها مع حلول الليل." },

{ timer: 30, text: "السماء الليلية بدت كسجادة مطرزة بالنار." },
{ timer: 30, text: "الظلال رقصت على إيقاع شمعة مرتجفة." },
{ timer: 30, text: "بومة راقبت من علٍ بصبر حكيم." },
{ timer: 30, text: "النهر غنّى ألحاناً لم تُكتب بعد." },
{ timer: 35, text: "السحب ذابت في دموع فضية." },
{ timer: 30, text: "طفل نام محتضناً حلماً مستحيلاً." },
{ timer: 30, text: "الأفق تلألأ كأنه وعد بعيد." },
{ timer: 30, text: "النجوم أرشدت مسافرين غير مرئيين." },
{ timer: 30, text: "زفرة عبرت المدينة مثل نسيم لطيف." },
{ timer: 30, text: "الليل أغمض عيني العالم برفق." }
];
export const paragraphs_ru = [
    { timer: 30, text: "Небо раскрылось, словно ткань из серебра, дыша медленно и глубоко." },
{ timer: 30, text: "Деревья шептали песни, которые слышал только ветер." },
{ timer: 30, text: "Река несла отражение луны, как тайну, спрятанную в воде." },
{ timer: 30, text: "Одинокий фонарь охранял улицу, как усталый страж." },
{ timer: 35, text: "Горы укрылись туманом, словно одеялом из облаков." },
{ timer: 30, text: "Часы били, и звук отзывался эхом в сердце." },
{ timer: 30, text: "Окна светились, как глаза, бодрствующие в темноте." },
{ timer: 30, text: "Море дышало медленно, мечтая о звёздах." },
{ timer: 30, text: "Кошка пересекла крышу, оставив следы тишины." },
{ timer: 30, text: "Колокола зазвонили, и воздух наполнился воспоминаниями." },

{ timer: 30, text: "Горизонт согнулся, обнимая последний луч солнца." },
{ timer: 30, text: "Тени вытянулись, словно хотели достать до неба." },
{ timer: 30, text: "Ребёнок пускал пузыри, похожие на крошечные планеты." },
{ timer: 30, text: "Лес шептал забытые имена." },
{ timer: 35, text: "Дождь рисовал идеальные круги на поверхности пруда." },
{ timer: 30, text: "Одинокая птица прочертила в небе огненную линию." },
{ timer: 30, text: "Звёзды зажглись, как старые фонари." },
{ timer: 30, text: "Ветер унёс лепестки, похожие на осколки луны." },
{ timer: 30, text: "Каменный мост хранил истории в своём молчании." },
{ timer: 30, text: "Облака раскрылись, как страницы тайной книги." },

{ timer: 30, text: "Рассвет пришёл медленно, как сдержанный вздох." },
{ timer: 30, text: "Волны разбивались в ритме спящего сердца." },
{ timer: 30, text: "Маяк вращался, рисуя круги надежды." },
{ timer: 30, text: "Поле пахло влажной землёй и древними обещаниями." },
{ timer: 35, text: "Светлячки зажгли ночь, как хор звёзд." },
{ timer: 30, text: "Далёкий поезд пел свою прощальную песню." },
{ timer: 30, text: "Горы отражали невозможный синий цвет." },
{ timer: 30, text: "Тишина легла тяжёлым бархатным покрывалом." },
{ timer: 30, text: "Собака лаяла на луну, будто могла её достать." },
{ timer: 30, text: "Пустые улицы хранили невидимые шаги." },

{ timer: 30, text: "Солнце спряталось за занавесом золотых облаков." },
{ timer: 30, text: "Колокола деревни отметили время без хозяина." },
{ timer: 30, text: "Скрытая река текла под спящей деревней." },
{ timer: 30, text: "Воздух пах свежим хлебом и покоем." },
{ timer: 35, text: "Звёзды отражались в лужах, как разбитые зеркала." },
{ timer: 30, text: "Колибри завис, бросая вызов времени." },
{ timer: 30, text: "Горы окрасились пурпуром на закате." },
{ timer: 30, text: "Ветер играл со шторами, как любопытный ребёнок." },
{ timer: 30, text: "Одинокий корабль скользил к горизонту." },
{ timer: 30, text: "Цветы закрыли глаза с приходом ночи." },

{ timer: 30, text: "Ночное небо выглядело, как ковёр, вышитый огнём." },
{ timer: 30, text: "Тени танцевали в такт дрожащей свече." },
{ timer: 30, text: "Сова наблюдала сверху, мудрая и терпеливая." },
{ timer: 30, text: "Река пела песни, которых никто не писал." },
{ timer: 35, text: "Облака растаяли в серебряных слезах." },
{ timer: 30, text: "Ребёнок спал, обняв невозможный сон." },
{ timer: 30, text: "Горизонт сиял, как далёкое обещание." },
{ timer: 30, text: "Звёзды вели невидимых странников." },
{ timer: 30, text: "Вздох прошёл по городу, как лёгкий ветер." },
{ timer: 30, text: "Ночь закрыла глаза мира с нежностью." }
];

export const paragraphs_de =[
    { timer: 30, text: "Der Himmel öffnete sich wie ein Tuch aus Silber und atmete langsam." },
{ timer: 30, text: "Die Bäume flüsterten Lieder, die nur der Wind verstand." },
{ timer: 30, text: "Der Fluss trug das Spiegelbild des Mondes wie ein verborgenes Geheimnis." },
{ timer: 30, text: "Eine einsame Laterne bewachte die Straße wie ein müder Wächter." },
{ timer: 35, text: "Die Berge hüllten sich in Nebel wie in eine Decke aus Wolken." },
{ timer: 30, text: "Die Uhr schlug, und der Klang hallte tief im Herzen wider." },
{ timer: 30, text: "Fenster leuchteten wie wachsame Augen in der Dunkelheit." },
{ timer: 30, text: "Das Meer atmete langsam, als träumte es von Sternen." },
{ timer: 30, text: "Eine Katze überquerte das Dach und hinterließ Spuren der Stille." },
{ timer: 30, text: "Die Glocken läuteten, und die Luft füllte sich mit Erinnerungen." },

{ timer: 30, text: "Der Horizont beugte sich, um den letzten Sonnenstrahl zu umarmen." },
{ timer: 30, text: "Die Schatten streckten sich, als wollten sie den Himmel berühren." },
{ timer: 30, text: "Ein Kind blies Seifenblasen, die wie kleine Planeten schwebten." },
{ timer: 30, text: "Der Wald flüsterte vergessene Namen." },
{ timer: 35, text: "Der Regen zeichnete perfekte Kreise auf den Teich." },
{ timer: 30, text: "Ein einsamer Vogel zog eine feurige Linie durch den Himmel." },
{ timer: 30, text: "Die Sterne entzündeten sich wie alte Laternen." },
{ timer: 30, text: "Der Wind trug Blütenblätter wie Splitter des Mondes davon." },
{ timer: 30, text: "Eine Steinbrücke bewahrte Geschichten in ihrem Schweigen." },
{ timer: 30, text: "Die Wolken öffneten sich wie Seiten eines geheimen Buches." },

{ timer: 30, text: "Die Morgendämmerung kam langsam wie ein zurückgehaltener Seufzer." },
{ timer: 30, text: "Die Wellen brachen im Rhythmus eines schlafenden Herzens." },
{ timer: 30, text: "Ein Leuchtturm drehte sich und malte Kreise der Hoffnung." },
{ timer: 30, text: "Das Feld roch nach feuchter Erde und alten Versprechen." },
{ timer: 35, text: "Glühwürmchen erhellten die Nacht wie ein Chor von Sternen." },
{ timer: 30, text: "Ein ferner Zug sang sein Abschiedslied in der Dunkelheit." },
{ timer: 30, text: "Die Berge spiegelten ein unmögliches Blau." },
{ timer: 30, text: "Die Stille lag schwer wie ein Samtumhang." },
{ timer: 30, text: "Ein Hund bellte den Mond an, als könnte er ihn erreichen." },
{ timer: 30, text: "Leere Straßen bewahrten unsichtbare Schritte." },

{ timer: 30, text: "Die Sonne verbarg sich hinter einem Vorhang aus goldenen Wolken." },
{ timer: 30, text: "Die Dorfkirche schlug eine Zeit ohne Besitzer." },
{ timer: 30, text: "Ein verborgener Fluss floss unter der schlafenden Stadt." },
{ timer: 30, text: "Die Luft roch nach frischem Brot und Frieden." },
{ timer: 35, text: "Die Sterne spiegelten sich in Pfützen wie zerbrochene Spiegel." },
{ timer: 30, text: "Ein Kolibri schwebte, trotzig gegen die Zeit." },
{ timer: 30, text: "Die Berge färbten sich purpurrot im Abendlicht." },
{ timer: 30, text: "Der Wind spielte mit den Vorhängen wie ein neugieriges Kind." },
{ timer: 30, text: "Ein einsames Schiff glitt dem Horizont entgegen." },
{ timer: 30, text: "Die Blumen schlossen ihre Augen mit Einbruch der Nacht." },

{ timer: 30, text: "Der Nachthimmel sah aus wie ein Teppich aus Feuerfäden." },
{ timer: 30, text: "Die Schatten tanzten im Takt einer flackernden Kerze." },
{ timer: 30, text: "Eine Eule wachte von oben, weise und geduldig." },
{ timer: 30, text: "Der Fluss sang Lieder, die niemand geschrieben hatte." },
{ timer: 35, text: "Die Wolken lösten sich in silbernen Tränen auf." },
{ timer: 30, text: "Ein Kind schlief, umarmt von einem unmöglichen Traum." },
{ timer: 30, text: "Der Horizont leuchtete wie ein fernes Versprechen." },
{ timer: 30, text: "Die Sterne führten unsichtbare Reisende." },
{ timer: 30, text: "Ein Seufzer zog durch die Stadt wie ein sanfter Wind." },
{ timer: 30, text: "Die Nacht schloss die Augen der Welt mit Zärtlichkeit." }
];

/*const paragraphs_shorter = [
  { timer: 30, text: "The sun dipped below the horizon, painting the sky in shades of orange and purple." },
  { timer: 30, text: "A gentle breeze carried the scent of jasmine through the quiet streets." },
  { timer: 35, text: "She opened the old book, its pages yellowed with time and filled with forgotten stories." },
  { timer: 30, text: "The city buzzed with life, neon lights flickering against the night sky." },
  { timer: 35, text: "Raindrops tapped softly against the window, a lullaby for the restless mind." },
  { timer: 35, text: "He walked along the shore, leaving footprints that the waves quickly erased." },
  { timer: 30, text: "The mountain stood tall and silent, a guardian of the valley below." },
  { timer: 30, text: "Children’s laughter echoed in the park, mingling with the chirping of birds." },
  { timer: 30, text: "The clock ticked steadily, marking the passage of moments too easily lost." },
  { timer: 30, text: "She sipped her tea slowly, savoring the warmth that spread through her hands." },
  { timer: 45, text: "The library smelled of paper and ink, a sanctuary for curious souls." },
  { timer: 50, text: "Stars scattered across the sky like diamonds on a velvet canvas." },
  { timer: 20, text: "He adjusted his glasses, focusing on the puzzle that refused to be solved." },
  { timer: 60, text: "The marketplace was alive with colors, sounds, and the aroma of spices." },
  { timer: 30, text: "A cat stretched lazily in the sunbeam, purring with contentment." },
  { timer: 30, text: "The train rumbled forward, carrying dreams and strangers alike." },
  { timer: 30, text: "She traced her finger along the map, imagining journeys yet to come." },
  { timer: 30, text: "The fire crackled in the hearth, casting dancing shadows on the walls." },
  { timer: 30, text: "He paused at the crossroads, uncertain which path would lead him home." },
  { timer: 30, text: "The garden bloomed in a riot of colors, a celebration of spring’s return." }
];
*/
    
